# Generated by Django 4.1.7 on 2023-08-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('product_description', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='product-image')),
            ],
        ),
    ]
